import './globals.css'
import Nav from '@/components/Nav'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="h-screen w-screen">
        <div className="p-10 xl:px-24">
          <Nav />
          {children}
        </div>
      </body>
    </html>
  )
}
